---
title: "Primer Parcial"
subtitle: Simulación Digital - Grupo H1
output:
  html_document:
    df_print: paged
  pdf_document: default
  html_notebook: default
---

2170688- Brayan Rodolfo Barajas Ochoa

1. Para esto, se tiene en cuenta que:

$$ x^2+y^2\leq1\;\land\; (x-1)^2+(y-1)^2\leq1  $$

```{r}
f_sup <- function(x,y){
  x^2+y^2
}
f_inf <- function(x,y){
  (x-1)^2+(y-1)^2
}

n=1000
exitos=0
for(i in 1:n){
u<-runif(1)
v<-runif(1)
if(f_inf(u,v)<=1 & f_sup(u,v)<=1){
  exitos=exitos+1
}
}
area=exitos/n
print(area)
```

Otra forma: la parte superior de la región está delimitada por $y=\sqrt{1-x^2}$, mientras que la inferior está delimitada por $y=-\sqrt{1-(x-1)^2}+1$ en el intervalo $[0,1]$.
Por lo que se puede definir la integral como:

$$\int_{0}^{1} \left(\sqrt{1-x^2}-\left(-\sqrt{1-(x-1)^2}+1\right)\right) \,dx$$

Esta integral se puede realizar por medio de Montecarlo:

```{r}
f_inf <- function(x){
  -sqrt(1-(x-1)^2)+1
}
f_sup <- function(x){
  sqrt(1-x^2)
}

n=1000
u<-runif(n)
#Se hace el calculo para cada valor con la respectiva sustitucion
g<-f_sup(u)-f_inf(u)
area=mean(g)
print(area)
```
2.Para simular esto, se hace el siguiente código:

```{r}
juego<-function(){ #Funcion que ejecuta un juego o experimento
  u1<-floor(runif(1,min=1,max=7)) #Valor del primer dado
  u2<-floor(runif(1,min=1,max=7)) #Valor del segundo dado
  total<-u1+u2 #Suma de los dados
  if(total==7 || total==11){ #Si es igual a 7 o 11, gana
    exito=1
  }
  else if(total==2 || total==3 || total==12){ #Si es igual a 2, 3 o 12, pierde
    exito=0
  }
  else{ #Si no saca alguno de los valores antes mencionados
    tirada=total #Se toma la suma como el valor de tirada
    prox=1
    while(prox==1){ #Mientras no haya un resultado, se vuelve a lanzar
      u1<-floor(runif(1,min=1,max=7)) #Se lanca de nuevo el primer dado
      u2<-floor(runif(1,min=1,max=7)) #Se lanza de nuevo el segundo dado
      total<-u1+u2 #Se suman los dados
      if(total==tirada){ #Si es igual al valor de la primera tirada, gana y termina el ciclo
        exito=1
        prox=0 
      }
      else if(total==7){ #Si es igual al 7, pierde y termina el ciclo
        exito=0
        prox=0
      }
    }
  }
  return(exito)
}
```

```{r}
n=10000
exitos=0
for(i in 1:n){ #Se realizan n cantidad de experimentos o juegos
  exitos=exitos+juego() #Se cuenta la cantidad de exitos
}
probabilidad=exitos/n #Se calcula la probabilidad
print(probabilidad)
```

